project:
  type: website

website:
  title: "Rowshni Farnaz Fatema - Business Analytics Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rows0001
format:
  html:
    theme: cosmo
    css: styles.css



