project:
  type: website

website:
  title: "Rowshni Farnaz Fatema - Business Analytics Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rows0001
format:
  html:
    theme: cosmo
    light:
      background: "#ffffff"  # White background for better readability
      text: "#333333"  # Dark text color for contrast
      primary: "#0056b3"  # Blue for links/headings
    css: styles.css



